scrape_configs:
  - job_name: 'docker'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
       - source_labels: [__meta_docker_container_label_metrics_scrape]
         regex: true
         action: keep
       - source_labels: [__meta_docker_container_label_com_docker_compose_service]
         target_label: job
       - source_labels: [__meta_docker_container_label_com_docker_compose_project]
         target_label: project
       - action: replace
         regex: (.+)
         source_labels:
         - __meta_docker_container_label_metrics_path
         target_label: __metrics_path__
       - action: replace
         regex: ([^:]+)(?::\d+)?;(\d+)
         replacement: $1:$2
         source_labels:
         - __address__
         - __meta_docker_container_label_metrics_port
         target_label: __address__
       - source_labels: [__meta_docker_container_label_metrics_network]
         target_label: network
